POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curs"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/3debd0ad-5995-4825-8ed7-2b6655596585